apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:6.5.5
        resources:
          limits:
            memory: "128Mi"
            cpu: "800m"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: wp-data
          mountPath: /var/www/html
        envFrom:
          - secretRef:
              name: wp-secret
      volumes:
      - name: wp-data
        persistentVolumeClaim:
          claimName: wp-pvc
