apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: wp-secret
data:
  WORDPRESS_DB_HOST: ZGItbXlzcWw=
  WORDPRESS_DB_USER: d29yZHByZXNz
  WORDPRESS_DB_PASSWORD: cm9vdA==
  WORDPRESS_DB_NAME: d29yZHByZXNzcHJvamV0